name: KMIR

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/kmir.yml'
      - 'kmir-proofs/**'

env:
  KMIR_VERSION: "ubuntu-jammy-0.4.226"

jobs:
  run-kmir-proofs:
    name: Run KMIR proofs
    runs-on: ubuntu-latest
    env:
      container_name: "kmir-${{ github.run_id }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Challenge 11 Proofs
        run: |
          docker run --rm -t \
            --name ${{ env.container_name }} \
            -w /home/kmir/workspace \
            -u $(id -u):$(id -g) \
            -v $PWD:/home/kmir/workspace \
            runtimeverificationinc/kmir:${{ env.KMIR_VERSION }} \
            kmir-proofs/0011-floats-ints/run-proofs.sh

  run-kmir-proofs-negative:
    name: Run KMIR negative proofs
    runs-on: ubuntu-latest
    env:
      container_name: "kmir-neg-${{ github.run_id }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Challenge 11 Negative Proofs
        run: |
          docker run --rm -t \
            --name ${{ env.container_name }} \
            -w /home/kmir/workspace \
            -u $(id -u):$(id -g) \
            -v $PWD:/home/kmir/workspace \
            runtimeverificationinc/kmir:${{ env.KMIR_VERSION }} \
            kmir-proofs/0011-floats-ints/run-proofs.sh --negative
